package FrontEnd;


import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Enzo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form FrontEnd
     */
    public Main() {
        initComponents();
    }
    private boolean IsFloat(JTextField TextField){
        try{
            float f = Float.parseFloat(TextField.getText());
            return true;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Valor informado não aceito!");
            return false;
        }
    }
    private boolean IsSelected(JComboBox ComboBox, String Campo){
        if(ComboBox.getSelectedItem()== null){
            JOptionPane.showMessageDialog(this, "Selecionar uma opção para o campo " + Campo + ".");
            ComboBox.requestFocus();
            return false;
    }
        else{
            return true;
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalariobase = new javax.swing.JLabel();
        txtSalariobase = new javax.swing.JTextField();
        lblPossuifilhos = new javax.swing.JLabel();
        cbPossuifilhos = new javax.swing.JComboBox<>();
        lblClasses = new javax.swing.JLabel();
        cbClasses = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        lblValorsalariobase = new javax.swing.JLabel();
        txtValorsalariobase = new javax.swing.JTextField();
        lblValordaclasse = new javax.swing.JLabel();
        txtValordaclasse = new javax.swing.JTextField();
        lblValordobeneficiodovalealimentacao = new javax.swing.JLabel();
        txtValordobeneficiodovalealealimentacao = new javax.swing.JTextField();
        lblValordobeneficiodovaletransporte = new javax.swing.JLabel();
        txtValordobeneficiodovaletransporte = new javax.swing.JTextField();
        lblTotaldosbeneficiosaplicados = new javax.swing.JLabel();
        txtTotaldosbeneficiosaplicados = new javax.swing.JTextField();
        lblDescontoaplicadodoir = new javax.swing.JLabel();
        txtDescontoaplicadoir = new javax.swing.JTextField();
        lblDescontoaplicadoinss = new javax.swing.JLabel();
        txtDescontoaplicadoinss = new javax.swing.JTextField();
        lblSalariobruto = new javax.swing.JLabel();
        txtSalariobruto = new javax.swing.JTextField();
        lblSalarioliquido = new javax.swing.JLabel();
        txtSalarioliquido = new javax.swing.JTextField();
        lblTotaldedescontosaplicados = new javax.swing.JLabel();
        txtTotaldedescontosaplicados = new javax.swing.JTextField();
        lblValorfilhos = new javax.swing.JLabel();
        txtValorfilhos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSalariobase.setText("Salário base");

        lblPossuifilhos.setText("Possui filhos");

        cbPossuifilhos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cbPossuifilhos.setSelectedIndex(-1);

        lblClasses.setText("Classes");

        cbClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classe 1", "Classe 2", "Classe 3" }));
        cbClasses.setSelectedIndex(-1);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblValorsalariobase.setText("Valor do salário base");

        txtValorsalariobase.setEditable(false);

        lblValordaclasse.setText("Valor da classe");

        txtValordaclasse.setEditable(false);

        lblValordobeneficiodovalealimentacao.setText("Valor do beneficio do vale alimentação");

        txtValordobeneficiodovalealealimentacao.setEditable(false);

        lblValordobeneficiodovaletransporte.setText("Valor do beneficio do vale transporte");

        txtValordobeneficiodovaletransporte.setEditable(false);

        lblTotaldosbeneficiosaplicados.setText("Total dos beneficios aplicados");

        txtTotaldosbeneficiosaplicados.setEditable(false);

        lblDescontoaplicadodoir.setText("Desconto aplicado do IR");

        txtDescontoaplicadoir.setEditable(false);

        lblDescontoaplicadoinss.setText("Desconto aplicado INSS");

        txtDescontoaplicadoinss.setEditable(false);

        lblSalariobruto.setText("Salário bruto");

        txtSalariobruto.setEditable(false);

        lblSalarioliquido.setText("Salário Liquido");

        txtSalarioliquido.setEditable(false);

        lblTotaldedescontosaplicados.setText("Total de descontos aplicados");

        txtTotaldedescontosaplicados.setEditable(false);

        lblValorfilhos.setText("Valor do beneficio filhos");

        txtValorfilhos.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorsalariobase)
                            .addComponent(txtValorsalariobase, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescontoaplicadoir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescontoaplicadodoir)
                            .addComponent(txtDescontoaplicadoinss, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescontoaplicadoinss))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblValordaclasse)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValordaclasse, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalariobruto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSalariobruto)
                                    .addComponent(txtSalarioliquido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSalarioliquido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotaldosbeneficiosaplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotaldosbeneficiosaplicados)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtValordobeneficiodovalealealimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValordobeneficiodovalealimentacao)
                                        .addComponent(lblValordobeneficiodovaletransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtValordobeneficiodovaletransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTotaldedescontosaplicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTotaldedescontosaplicados)
                                    .addComponent(lblValorfilhos)
                                    .addComponent(txtValorfilhos))))
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalariobase)
                            .addComponent(txtSalariobase, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPossuifilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPossuifilhos)
                            .addComponent(lblClasses)
                            .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSalariobase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalariobase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPossuifilhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPossuifilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorsalariobase)
                    .addComponent(lblValordaclasse)
                    .addComponent(lblValordobeneficiodovalealimentacao)
                    .addComponent(lblTotaldedescontosaplicados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorsalariobase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValordaclasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValordobeneficiodovalealealimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotaldedescontosaplicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValordobeneficiodovaletransporte)
                    .addComponent(lblDescontoaplicadodoir)
                    .addComponent(lblSalariobruto)
                    .addComponent(lblValorfilhos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValordobeneficiodovaletransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescontoaplicadoir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalariobruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorfilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotaldosbeneficiosaplicados)
                    .addComponent(lblDescontoaplicadoinss)
                    .addComponent(lblSalarioliquido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotaldosbeneficiosaplicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSalarioliquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescontoaplicadoinss))
                .addGap(0, 132, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        if (IsFloat(txtSalariobase)){
            float sb = Float.parseFloat(txtSalariobase.getText());
            if(sb > 0){
                  if(IsSelected(cbPossuifilhos, "Possui filhos!")){
                       if(IsSelected(cbClasses, "Classes")){
                           float vclasse;
                           float va = 472.47f;
                           float beneficiof;
                           float vt = 0;
                           float totalb;
                           float sc;
                           float ir;
                           float p;
                           float inss;
                           float sbruto;
                           float sliquido;
                           float descontoap;
                           txtValorsalariobase.setText(String.format("%.2f",sb));
                           if(cbClasses.getSelectedIndex() == 0){
                                vclasse = 489.70f;
                                txtValordaclasse.setText(String.format("%.2f",vclasse));
                          }else if(cbClasses.getSelectedIndex()== 1){
                                vclasse = 731.67f;
                                txtValordaclasse.setText(String.format("%.2f", vclasse));
                          }else {
                                vclasse = 1223.31f;
                                txtValordaclasse.setText(String.format("%.2f", vclasse));
                          }
                           txtValordobeneficiodovalealealimentacao.setText(String.valueOf(va));
                           if(cbPossuifilhos.getSelectedIndex()== 0){
                                beneficiof = 131.18f;
                                txtValorfilhos.setText(String.format("%.2f",beneficiof));
                           }else {
                                beneficiof = 0f;
                                txtValorfilhos.setText(String.format("%.2f", beneficiof));
                           }if(sb<=1039.00f){
                                vt = 285.85f;
                                txtValordobeneficiodovaletransporte.setText(String.format("%.2f",vt));
                           }else if(sb <=1546.50f){
                                vt = 201.43f;
                                txtValordobeneficiodovaletransporte.setText(String.format("%.2f",vt));
                           }else if(sb <=2146.50f){
                                vt = 185.71f;
                                txtValordobeneficiodovaletransporte.setText(String.format("%.2f",vt));
                           }else if (sb <= 3002.17f){
                                vt = 121.33f;
                                txtValordobeneficiodovaletransporte.setText(String.format("%.2f",vt));
                           }else if (sb <= 3702.29f){
                                vt = 85.18f;
                                txtValordobeneficiodovaletransporte.setText(String.format("%.2f",vt));
                           }else if (sb > 3702.29f){
                                vt = 78.41f;
                                txtValordobeneficiodovaletransporte.setText(String.format("%.2f",vt));
                           }
                            totalb = vt + beneficiof + va;
                            txtTotaldosbeneficiosaplicados.setText(String.format("%.2f", totalb));
                            sc = sb + vclasse;
                            if(sc <= 1499.15f){
                                ir = 0f;
                                txtDescontoaplicadoir.setText(String.format("%.2f",ir));
                            }
                            else if(sc <= 2146.75f){
                                ir =  sc * (7.5f/100);
                                txtDescontoaplicadoir.setText(String.format("%.2f", ir));
                            }else if(sc <= 2995.70f){
                                ir = sc * (15f/100);
                                txtDescontoaplicadoir.setText(String.format("%.2f", ir));
                            }else if(sc <= 3441.16f){
                                ir = sc * (22f/100);
                                txtDescontoaplicadoir.setText(String.format("%.2f", ir));
                            }else if(sc <= 4543.11f){
                                ir = sc *(24.50f/100);
                                txtDescontoaplicadoir.setText(String.format("%.2f",ir));
                            }else{
                                ir = sc * (28.50f/100);
                                txtDescontoaplicadoir.setText(String.format("%.2f",ir));
                            }
                            if(sc <= 1417.15f){
                                inss = sc * (8f/100);
                                txtDescontoaplicadoinss.setText(String.format("%.2f",inss));
                            }else if(sc <= 2195.12f){
                                inss = sc* (9f/100);
                                txtDescontoaplicadoinss.setText(String.format("%.2f", inss));
                            }else if (sc <= 3396.11f){
                                inss = sc * (11f/100);
                                txtDescontoaplicadoinss.setText(String.format("%.2f", inss));
                            }else{
                                inss = sc * (14f/100);
                                txtDescontoaplicadoinss.setText(String.format("%.2f", inss));
                            }
                            sbruto = sb + va + beneficiof + vt + vclasse;
                            txtSalariobruto.setText(String.format("%.2f", sbruto));
                            sliquido = ((sb + vclasse) - (ir + inss)) + va + vt + beneficiof;
                            txtSalarioliquido.setText(String.format("%.2f", sliquido));
                            descontoap = ir + inss;
                            txtTotaldedescontosaplicados.setText(String.format("%.2f",descontoap));
                        
              
            }
            }    
            }
            else{
                JOptionPane.showMessageDialog(this, "Valor informado não aceito!");
                }
            }
            
        else{
            txtSalariobase.setText("");
            txtSalariobase.requestFocus();
        }
       
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbClasses;
    private javax.swing.JComboBox<String> cbPossuifilhos;
    private javax.swing.JLabel lblClasses;
    private javax.swing.JLabel lblDescontoaplicadodoir;
    private javax.swing.JLabel lblDescontoaplicadoinss;
    private javax.swing.JLabel lblPossuifilhos;
    private javax.swing.JLabel lblSalariobase;
    private javax.swing.JLabel lblSalariobruto;
    private javax.swing.JLabel lblSalarioliquido;
    private javax.swing.JLabel lblTotaldedescontosaplicados;
    private javax.swing.JLabel lblTotaldosbeneficiosaplicados;
    private javax.swing.JLabel lblValordaclasse;
    private javax.swing.JLabel lblValordobeneficiodovalealimentacao;
    private javax.swing.JLabel lblValordobeneficiodovaletransporte;
    private javax.swing.JLabel lblValorfilhos;
    private javax.swing.JLabel lblValorsalariobase;
    private javax.swing.JTextField txtDescontoaplicadoinss;
    private javax.swing.JTextField txtDescontoaplicadoir;
    private javax.swing.JTextField txtSalariobase;
    private javax.swing.JTextField txtSalariobruto;
    private javax.swing.JTextField txtSalarioliquido;
    private javax.swing.JTextField txtTotaldedescontosaplicados;
    private javax.swing.JTextField txtTotaldosbeneficiosaplicados;
    private javax.swing.JTextField txtValordaclasse;
    private javax.swing.JTextField txtValordobeneficiodovalealealimentacao;
    private javax.swing.JTextField txtValordobeneficiodovaletransporte;
    private javax.swing.JTextField txtValorfilhos;
    private javax.swing.JTextField txtValorsalariobase;
    // End of variables declaration//GEN-END:variables
}
